package proxy:util;

interface debug {
  print: func(x: string);
  eprint: func(x: string);
  get-random: func() -> list<u8>;
}

interface dialog {
  print: func(x:string);
  read-selection: func(dep: u32, prompt: string, items: list<string>) -> u32;
  read-bool: func(dep: u32) -> string;
  read-string: func(dep: u32) -> string;
  read-u8: func(dep: u32) -> string;
  read-u16: func(dep: u32) -> string;
  read-u32: func(dep: u32) -> string;
  read-u64: func(dep: u32) -> string;
  read-s8: func(dep: u32) -> string;
  read-s16: func(dep: u32) -> string;
  read-s32: func(dep: u32) -> string;
  read-s64: func(dep: u32) -> string;
  read-f32: func(dep: u32) -> string;
  read-f64: func(dep: u32) -> string;
  read-char: func(dep: u32) -> string;
}

world crate-debug {
  export debug;
}

world host-dialog {
  import dialog;
}