package proxy:util;

interface debug {
  print: func(x: string);
  eprint: func(x: string);
  get-random: func() -> list<u8>;
}

interface dialog {
  prompt: func(x: string);
  input: func(x: string) -> string;
}

world crate-debug {
  export debug;
}

world host-dialog {
  import dialog;
}