package proxy:util;

interface debug {
  print: func(x: string);
  eprint: func(x: string);
  get-random: func() -> list<u8>;
}

interface dialog {
  print: func(x:string);
  read-string: func(dep: u32) -> string;
  read-bool: func(dep: u32) -> string;
}

world crate-debug {
  export debug;
}

world host-dialog {
  import dialog;
}