use anyhow::Result;
use heck::ToKebabCase;
use quote::quote;
use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;
use syn::{
    File, Ident, Item, ItemEnum, ItemStruct, ItemTrait, Signature, TraitItem, Type, parse_quote,
    visit_mut::VisitMut,
};
use util::{
    FullTypePath, ResourceFuncKind, extract_arg_info, get_owned_type, get_resource_from_trait_name,
    get_return_type, make_path, toggle_wrapped_module, wit_func_name,
};

mod dialog;
mod fuzz;
mod parse;
mod record;
mod replay;
pub mod util;

#[derive(clap::Parser)]
pub struct GenerateArgs {
    /// The path to the binding file generated by wit-bindgen.
    pub bindings: PathBuf,
    /// Specifies the type of the WIT component.
    pub mode: GenerateMode,
    /// The path to the output file.
    #[arg(short, long, default_value("lib.rs"))]
    pub output_file: PathBuf,
    #[arg(long)]
    pub use_custom_allocator: bool,
}
#[derive(clap::ValueEnum, clap::Parser, Clone)]
pub enum GenerateMode {
    /// An arbitrary component, we can only generate an empty stub.
    Stubs,
    /// An instrument component which imports and exports the same interface.
    /// The generated code will redirect the export interface to call the corresponding import interface.
    Instrument,
    /// An instrument component which records all import calls.
    Record,
    /// A virtualized component with no imports, with implementation for replay.
    Replay,
    /// A virtualized component with no imports, with implementation for fuzzing.
    Fuzz,
    /// A virtualized component with no imports, with implementation for dialog.
    Dialog,
}
impl GenerateMode {
    pub fn is_instrument(&self) -> bool {
        matches!(self, GenerateMode::Instrument | GenerateMode::Record)
    }
}

pub struct State {
    pub mode: GenerateMode,
    pub traits: BTreeMap<Vec<String>, Vec<ItemTrait>>,
    pub types: BTreeMap<Vec<String>, Vec<TypeInfo>>,
    pub funcs: BTreeMap<Vec<String>, BTreeMap<Option<String>, Vec<Signature>>>,
    pub module_paths: BTreeSet<Vec<String>>,
    /// Full path of each public type alias to its target type.
    pub type_aliases: BTreeMap<Vec<String>, Type>,
    pub output: Vec<Item>,
}
pub enum TypeInfo {
    Struct(ItemStruct),
    Enum(ItemEnum),
    Resource(ItemStruct),
    Flag(ItemFlag),
}
pub struct ItemFlag {
    pub name: Ident,
    pub flags: Vec<Ident>,
}
/// An exported function of the main component, see `State::export_funcs`.
struct ExportFunc {
    /// WIT name, e.g. `ns:pkg/iface.func`
    display_name: String,
    /// Rust path to the function
    func: syn::Path,
    arg_names: Vec<Ident>,
    /// Owned argument types, e.g. `String` for `&str`
    arg_tys: Vec<Type>,
    /// Arguments at the call site, borrowed where the function expects a reference
    call_params: Vec<syn::Expr>,
    has_ret: bool,
}

/// Interface for converting resources between the generated components.
const CONVERSION_MODULE: &str = "exports::proxy::conversion::conversion";
/// Interface whose `start` function drives the main component's exports in virtualized modes.
const START_REPLAY_MODULE: &str = "exports::proxy::recorder::start_replay";

impl GenerateArgs {
    pub fn generate(&self) -> Result<()> {
        let file = std::fs::read_to_string(&self.bindings)?;
        let ast = syn::parse_file(&file)?;

        let mut state = State {
            mode: self.mode.clone(),
            traits: BTreeMap::new(),
            types: BTreeMap::new(),
            funcs: BTreeMap::new(),
            module_paths: BTreeSet::new(),
            type_aliases: BTreeMap::new(),
            output: Vec::new(),
        };
        state.generate_preamble();
        state.find_all_items(&ast.items, vec![]);
        state.generate_stubs();
        let trait_generator = crate::traits::TraitGenerator::new(&state);
        let traits = trait_generator.generate();
        drop(trait_generator);
        state.output.extend(traits);
        let mut file = state.into_output_file();
        if self.use_custom_allocator {
            // dlmalloc with a memory source that grows by bytes, for `--page-size=1`.
            let alloc = syn::parse_file(include_str!("../../assets/one_byte_page_alloc.rs"))?;
            let items = alloc.items;
            file.items.push(parse_quote! {
                #[cfg(all(not(target_feature = "atomics"), target_arch = "wasm32"))]
                mod one_byte_page_alloc { #(#items)* }
            });
        }
        let output = prettyplease::unparse(&file);
        std::fs::write(&self.output_file, output)?;
        Ok(())
    }
}
impl State {
    fn generate_stubs(&mut self) {
        for (module_path, traits) in &self.traits {
            for trait_item in traits {
                let impl_item = self.generate_impl_with_methods(trait_item, module_path);
                self.output.push(impl_item);
            }
        }
    }
    fn generate_preamble(&mut self) {
        let file: File = parse_quote! {
          mod bindings;
          use bindings::*;
          struct Stub;
          bindings::export!(Stub with_types_in bindings);
        };
        self.output = file.items;
    }
    fn generate_impl_with_methods(&self, trait_item: &ItemTrait, module_path: &[String]) -> Item {
        let trait_name = &trait_item.ident.to_string();
        let trait_path = make_path(module_path, trait_name);
        let resource = get_resource_from_trait_name(trait_name);
        let stub: syn::Path = match (&self.mode.is_instrument(), &resource) {
            (true, Some(resource)) => {
                let import_path = get_proxy_path(module_path);
                make_path(&import_path, resource)
            }
            (false, Some(_)) => parse_quote! { MockedResource },
            (_, _) => parse_quote! { Stub },
        };
        // Collect all method signatures from the trait
        let mut methods = Vec::new();
        for item in &trait_item.items {
            match item {
                TraitItem::Type(assoc_type) => {
                    let type_name = &assoc_type.ident;
                    let stub: syn::Path = if self.mode.is_instrument() {
                        let import_path = get_proxy_path(module_path);
                        make_path(&import_path, &type_name.to_string())
                    } else {
                        parse_quote! { MockedResource }
                    };
                    let impl_item = parse_quote! {
                        type #type_name = #stub;
                    };
                    methods.push(syn::ImplItem::Type(impl_item));
                }
                TraitItem::Fn(method) => {
                    let method_name = method.sig.ident.to_string();
                    if method_name.starts_with("_resource_")
                        || (method_name.starts_with("resource") && method_name.ends_with("_"))
                    {
                        continue;
                    }
                    let mut sig = method.sig.clone();
                    let mut transformer = FullTypePath { module_path };
                    transformer.visit_signature_mut(&mut sig);
                    let module_full_name = module_path.join("::");
                    if module_full_name == CONVERSION_MODULE {
                        let stub_impl = self.generate_conversion_func(&sig);
                        methods.push(syn::ImplItem::Fn(stub_impl));
                        continue;
                    }
                    let is_start = module_full_name == START_REPLAY_MODULE;
                    if is_start {
                        assert!(sig.ident == "start");
                    }
                    let stub_impl = match (&self.mode, is_start) {
                        (GenerateMode::Stubs, _) => parse_quote! {
                            #[allow(unused_variables)]
                            #sig {
                                unimplemented!()
                            }
                        },
                        (GenerateMode::Instrument | GenerateMode::Record, _) => {
                            self.generate_instrument_func(module_path, &sig, &resource)
                        }
                        (GenerateMode::Replay, false) => {
                            self.generate_replay_import_func(module_path, &sig, &resource)
                        }
                        (GenerateMode::Replay, true) => self.generate_replay_start_func(&sig),
                        (GenerateMode::Fuzz, false) => {
                            self.generate_fuzz_import_func(module_path, &sig, &resource)
                        }
                        (GenerateMode::Fuzz, true) => self.generate_fuzz_start_func(&sig),
                        (GenerateMode::Dialog, false) => {
                            self.generate_dialog_import_func(module_path, &sig, &resource)
                        }
                        (GenerateMode::Dialog, true) => self.generate_dialog_start_func(&sig),
                    };
                    methods.push(syn::ImplItem::Fn(stub_impl));
                }
                _ => (),
            }
        }
        parse_quote! {
            impl #trait_path for #stub {
                #(#methods)*
            }
        }
    }

    fn generate_conversion_func(&self, sig: &Signature) -> syn::ImplItemFn {
        let func_name = &sig.ident.to_string();
        let body = if func_name.starts_with("get_wrapped_") || func_name.starts_with("get_host_") {
            quote! { x.to_proxy() }
        } else if func_name.starts_with("get_mock_") {
            let resource = get_return_type(&sig.output).unwrap();
            let name = self.resource_name(&resource);
            quote! {
                #resource::new(MockedResource { handle, name: #name.to_string() })
            }
        } else {
            unreachable!()
        };
        parse_quote! {
            #sig {
                #body
            }
        }
    }
    /// The conversion interface refers to resources through type aliases, e.g.
    /// `WasiIoStreamsOutputStream = ...::wasi::io::streams::OutputStream`.
    /// Returns the WIT name of the aliased resource, e.g. `output-stream`.
    fn resource_name(&self, alias: &Type) -> String {
        let Type::Path(alias) = alias else {
            unreachable!()
        };
        let alias_path: Vec<_> = alias
            .path
            .segments
            .iter()
            .map(|s| s.ident.to_string())
            .collect();
        let Some(Type::Path(target)) = self.type_aliases.get(&alias_path) else {
            panic!("{} is not a type alias", alias_path.join("::"));
        };
        target
            .path
            .segments
            .last()
            .unwrap()
            .ident
            .to_string()
            .to_kebab_case()
    }
    /// Functions exported by the main component, which the `start` function of the virtualized
    /// modes calls. Resource methods are skipped.
    fn export_funcs(&self) -> Vec<ExportFunc> {
        let mut res = Vec::new();
        for (path, resources) in self
            .funcs
            .iter()
            .filter(|(path, _)| path[0] != "exports" && path[0] != "proxy")
        {
            for (resource, sigs) in resources {
                for sig in sigs {
                    let (kind, args) = extract_arg_info(sig);
                    if matches!(kind, Some(ResourceFuncKind::Method)) {
                        continue;
                    }
                    let arg_tys = args
                        .iter()
                        .map(|arg| {
                            let mut ty = arg.ty.clone();
                            FullTypePath { module_path: path }.visit_type_mut(&mut ty);
                            get_owned_type(&ty).unwrap_or(ty)
                        })
                        .collect();
                    let func_name = match resource {
                        Some(resource) => format!("{}::{}", resource, sig.ident),
                        None => sig.ident.to_string(),
                    };
                    res.push(ExportFunc {
                        display_name: wit_func_name(path, resource, &sig.ident, &kind),
                        func: make_path(path, &func_name),
                        arg_names: args.iter().map(|arg| arg.ident.clone()).collect(),
                        arg_tys,
                        call_params: args.iter().map(|arg| arg.call_param()).collect(),
                        has_ret: get_return_type(&sig.output).is_some(),
                    });
                }
            }
        }
        res
    }
    fn into_output_file(self) -> File {
        File {
            items: self.output,
            shebang: None,
            attrs: Vec::new(),
        }
    }
}

pub fn get_proxy_path(src_path: &[String]) -> Vec<String> {
    assert!(src_path.len() >= 3);
    let mut res = src_path.to_vec();
    let mut wrapped_idx = 0;
    if res[0] == "exports" {
        res.remove(0);
    } else {
        res.insert(0, "exports".to_string());
        wrapped_idx = 1;
    }
    res[wrapped_idx] = toggle_wrapped_module(&res[wrapped_idx]);
    res
}
