use crate::util::{
    FullTypePath, ResourceFuncKind, extract_arg_info, get_owned_type, get_resource_from_trait_name,
    get_return_type, make_path, wit_func_name,
};
use anyhow::Result;
use quote::quote;
use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;
use syn::{
    File, Ident, Item, ItemEnum, ItemStruct, ItemTrait, Signature, TraitItem, parse_quote,
    visit_mut::VisitMut,
};

#[derive(clap::Parser)]
pub struct GenerateArgs {
    /// The path to the binding file generated by wit-bindgen.
    pub bindings: PathBuf,
    /// Specifies the type of the WIT component.
    pub mode: GenerateMode,
    /// The path to the output file.
    #[arg(short, long, default_value("lib.rs"))]
    pub output_file: PathBuf,
}
#[derive(clap::ValueEnum, clap::Parser, Clone)]
pub enum GenerateMode {
    /// An arbitrary component, we can only generate an empty stub.
    Stubs,
    /// An instrument component which imports and exports the same interface.
    /// The generated code will redirect the export interface to call the corresponding import interface.
    Instrument,
    /// An instrument component which records all import calls.
    Record,
    /// A virtualized component with no imports. Currently only used for replay.
    Replay,
}
impl GenerateMode {
    pub fn is_instrument(&self) -> bool {
        matches!(self, GenerateMode::Instrument | GenerateMode::Record)
    }
}

pub struct State {
    pub mode: GenerateMode,
    pub traits: BTreeMap<Vec<String>, Vec<ItemTrait>>,
    pub types: BTreeMap<Vec<String>, Vec<TypeInfo>>,
    pub funcs: BTreeMap<Vec<String>, BTreeMap<Option<String>, Vec<Signature>>>,
    pub module_paths: BTreeSet<Vec<String>>,
    pub output: Vec<Item>,
}
pub enum TypeInfo {
    Struct(ItemStruct),
    Enum(ItemEnum),
    Resource(ItemStruct),
    Flag(ItemFlag),
}
pub struct ItemFlag {
    pub name: Ident,
    pub flags: Vec<Ident>,
}

impl GenerateArgs {
    pub fn generate(&self) -> Result<()> {
        let file = std::fs::read_to_string(&self.bindings)?;
        let ast = syn::parse_file(&file)?;

        let mut state = State {
            mode: self.mode.clone(),
            traits: BTreeMap::new(),
            types: BTreeMap::new(),
            funcs: BTreeMap::new(),
            module_paths: BTreeSet::new(),
            output: Vec::new(),
        };
        state.generate_preamble();
        state.find_all_items(&ast.items, vec![]);
        state.generate_stubs();
        let trait_generator = crate::traits::TraitGenerator::new(&state);
        let traits = trait_generator.generate();
        drop(trait_generator);
        state.output.extend(traits);
        let file = state.into_output_file();
        let output = prettyplease::unparse(&file);
        std::fs::write(&self.output_file, output)?;
        Ok(())
    }
}
impl State {
    fn generate_stubs(&mut self) {
        for (module_path, traits) in &self.traits {
            for trait_item in traits {
                let impl_item = self.generate_impl_with_methods(trait_item, module_path);
                self.output.push(impl_item);
            }
        }
    }
    fn generate_preamble(&mut self) {
        let file: File = parse_quote! {
          mod bindings;
          use bindings::*;
          struct Stub;
          bindings::export!(Stub with_types_in bindings);
        };
        self.output = file.items;
    }
    fn generate_impl_with_methods(&self, trait_item: &ItemTrait, module_path: &[String]) -> Item {
        let trait_name = &trait_item.ident.to_string();
        let trait_path = make_path(module_path, trait_name);
        let resource = get_resource_from_trait_name(trait_name);
        let stub: syn::Path = match (&self.mode.is_instrument(), &resource) {
            (true, Some(resource)) => {
                let import_path = get_proxy_path(module_path);
                make_path(&import_path, resource)
            }
            (false, Some(_)) => parse_quote! { MockedResource },
            (_, _) => parse_quote! { Stub },
        };
        // Collect all method signatures from the trait
        let mut methods = Vec::new();
        for item in &trait_item.items {
            match item {
                TraitItem::Type(assoc_type) => {
                    let type_name = &assoc_type.ident;
                    let stub: syn::Path = if self.mode.is_instrument() {
                        let import_path = get_proxy_path(module_path);
                        make_path(&import_path, &type_name.to_string())
                    } else {
                        parse_quote! { MockedResource }
                    };
                    let impl_item = parse_quote! {
                        type #type_name = #stub;
                    };
                    methods.push(syn::ImplItem::Type(impl_item));
                }
                TraitItem::Fn(method) => {
                    if method.sig.ident.to_string().starts_with("_resource_") {
                        continue;
                    }
                    let mut sig = method.sig.clone();
                    let mut transformer = FullTypePath { module_path };
                    transformer.visit_signature_mut(&mut sig);
                    let stub_impl = match self.mode {
                        GenerateMode::Stubs => parse_quote! {
                            #[allow(unused_variables)]
                            #sig {
                                unimplemented!()
                            }
                        },
                        GenerateMode::Instrument | GenerateMode::Record => {
                            if module_path.join("::") == "exports::proxy::conversion::conversion" {
                                self.generate_conversion_func(&sig)
                            } else {
                                self.generate_instrument_func(module_path, &sig, &resource)
                            }
                        }
                        GenerateMode::Replay => {
                            if module_path.join("::") == "exports::proxy::conversion::conversion" {
                                self.generate_conversion_func(&sig)
                            } else {
                                self.generate_replay_func(module_path, &sig, &resource)
                            }
                        }
                    };
                    methods.push(syn::ImplItem::Fn(stub_impl));
                }
                _ => (),
            }
        }
        parse_quote! {
            impl #trait_path for #stub {
                #(#methods)*
            }
        }
    }
    fn generate_replay_func(
        &self,
        module_path: &[String],
        sig: &Signature,
        resource: &Option<String>,
    ) -> syn::ImplItemFn {
        let func_name = &sig.ident;
        let is_export = module_path.join("::") == "exports::proxy::recorder::start_replay";
        if !is_export {
            let (kind, args) = extract_arg_info(sig);
            let arg_names = args.iter().map(|arg| &arg.ident);
            let display_name = wit_func_name(module_path, resource, func_name, &kind);
            let ret_ty = get_return_type(&sig.output);
            let replay_import = if let Some(ret_ty) = ret_ty {
                quote! {
                    let wave = proxy::recorder::replay::replay_import(Some(#display_name), Some(&args)).unwrap();
                    let ret: Value = wasm_wave::from_str(&<#ret_ty as ValueTyped>::value_type(), &wave).unwrap();
                    ret.to_rust()
                }
            } else {
                quote! {
                    let wave = proxy::recorder::replay::replay_import(Some(#display_name), Some(&args));
                    assert!(wave.is_none());
                }
            };
            let self_value = if matches!(kind, Some(ResourceFuncKind::Method)) {
                // Use ToValue::to_value to avoid the auto-deref from self.to_value()
                quote! { wasm_wave::to_string(&ToValue::to_value(&self)).unwrap(), }
            } else {
                quote! {}
            };
            parse_quote! {
                #sig {
                    let args = vec![#self_value #( wasm_wave::to_string(&#arg_names.to_value()).unwrap() ),*];
                    #replay_import
                }
            }
        } else {
            assert!(func_name == "start");
            let arms = self
                .funcs
                .iter()
                .filter(|(path, _)| path[0] != "exports" && path[0] != "proxy")
                .flat_map(|(path, resources)| {
                    resources.iter().flat_map(move |(resource, sigs)| {
                        sigs.iter().filter_map(move |sig| {
                            let (kind, args) = extract_arg_info(sig);
                            if matches!(kind, Some(ResourceFuncKind::Method)) {
                                return None;
                            }
                            let arg_name: Vec<_> = args.iter().map(|arg| &arg.ident).collect();
                            let arg_idx = args.iter().enumerate().map(|(idx, _)| quote! { args[#idx] });
                            let call_param = args.iter().map(|arg| arg.call_param());
                            let ty = args.iter().map(|arg| {
                                let mut ty = arg.ty.clone();
                                FullTypePath {
                                    module_path: path,
                                }.visit_type_mut(&mut ty);
                                if let Some(owned) = get_owned_type(&ty) {
                                    owned
                                } else {
                                    ty
                                }
                            });
                            let func_name = if let Some(resource) = resource {
                                format!("{}::{}", resource, sig.ident)
                            } else {
                                sig.ident.to_string()
                            };
                            let func = make_path(path, &func_name);
                            let display_name = wit_func_name(path, resource, &sig.ident, &kind);
                            let assert_ret = if get_return_type(&sig.output).is_none() {
                                quote! {
                                    assert!(res == ());
                                    proxy::recorder::replay::assert_export_ret(Some(#display_name), None);
                                }
                            } else {
                                quote! {
                                    let wave_res = wasm_wave::to_string(&res.to_value()).unwrap();
                                    proxy::recorder::replay::assert_export_ret(Some(#display_name), Some(&wave_res));
                                }
                            };
                            Some(quote! {
                                #display_name => {
                                    #(
                                        let arg_value: Value = wasm_wave::from_str(&<#ty as ValueTyped>::value_type(), &#arg_idx).unwrap();
                                        let #arg_name: #ty = arg_value.to_rust();
                                    )*
                                    let res = #func(#(#call_param),*);
                                    #assert_ret
                                }
                            })
                        })
                    })
                });
            parse_quote! {
                #sig {
                    while let Some((method, args)) = proxy::recorder::replay::replay_export() {
                        match method.as_str() {
                            #(#arms)*
                            _ => unreachable!(),
                        }
                        // clean up borrowed resources from input args
                        SCOPED_ALLOC.with(|alloc| {
                            alloc.borrow_mut().clear();
                        });
                    }
                }
            }
        }
    }
    fn generate_instrument_func(
        &self,
        module_path: &[String],
        sig: &Signature,
        resource: &Option<String>,
    ) -> syn::ImplItemFn {
        let func_name = &sig.ident;
        let (kind, args) = extract_arg_info(sig);
        let import_path = get_proxy_path(module_path);
        let import_sig = self
            .find_function(&import_path, resource, func_name)
            .unwrap();
        let (_, import_args) = extract_arg_info(import_sig);
        let arg_names = args.iter().map(|arg| &arg.ident);
        let call_args = args
            .iter()
            .zip(import_args.iter())
            .map(|(arg, import_arg)| -> syn::Expr {
                let ident = &arg.ident;
                if import_arg.is_borrowed {
                    parse_quote! { &#ident }
                } else {
                    parse_quote! { #ident }
                }
            });
        let (func, res): (syn::Expr, _) = match (resource.is_some(), &kind) {
            (true, Some(ResourceFuncKind::Method)) => {
                (parse_quote! { self.#func_name }, quote! { res.to_proxy() })
            }
            (true, Some(ResourceFuncKind::Constructor)) => {
                (parse_quote! { Self::#func_name }, quote! { res })
            }
            (true, None) => (parse_quote! { Self::#func_name }, quote! { res.to_proxy() }),
            (false, _) => (
                syn::parse_str(&format!("{}::{}", import_path.join("::"), func_name)).unwrap(),
                quote! { res.to_proxy() },
            ),
        };
        match &self.mode {
            GenerateMode::Instrument => parse_quote! {
                #sig {
                    let res = #func(#(#call_args.to_proxy()),*);
                    #res
                }
            },
            GenerateMode::Record => {
                let init_vec = if matches!(kind, Some(ResourceFuncKind::Method)) {
                    quote! { vec![wasm_wave::to_string(&ToValue::to_value(&self)).unwrap()] }
                } else {
                    quote! { Vec::new() }
                };
                let is_mut = if args.is_empty() {
                    quote! {}
                } else {
                    quote! { mut }
                };
                let display_name = wit_func_name(module_path, resource, func_name, &kind);
                let is_export = !module_path[1].starts_with("wrapped_");
                let record_ret = if get_return_type(&sig.output).is_none() {
                    quote! {
                        #func(#(#call_args),*);
                        proxy::recorder::record::record_ret(Some(#display_name), None, #is_export);
                    }
                } else {
                    quote! {
                       let res = #func(#(#call_args),*);
                       let wave_res = wasm_wave::to_string(&res.to_value()).unwrap();
                       proxy::recorder::record::record_ret(Some(#display_name), Some(&wave_res), #is_export);
                       #res
                    }
                };
                parse_quote! {
                    #sig {
                        let #is_mut params: Vec<String> = #init_vec;
                        #(
                            let #arg_names = #arg_names.to_proxy();
                            params.push(wasm_wave::to_string(&ToValue::to_value(&#arg_names)).unwrap());
                        )*
                        proxy::recorder::record::record_args(Some(#display_name), &params, #is_export);
                        #record_ret
                    }
                }
            }
            _ => unreachable!(),
        }
    }
    fn generate_conversion_func(&self, sig: &Signature) -> syn::ImplItemFn {
        let func_name = &sig.ident.to_string();
        let body = if func_name.starts_with("get_wrapped_") {
            quote! { x.to_proxy() }
        } else if func_name.starts_with("get_host_") {
            quote! { x.to_proxy() }
        } else if func_name.starts_with("get_mock_") {
            let resource = get_return_type(&sig.output).unwrap();
            // TODO: find a way to get resource name more reliably
            let name = func_name.split('_').last().unwrap();
            quote! {
                #resource::new(MockedResource { handle, name: #name.to_string() })
            }
        } else {
            unreachable!()
        };
        parse_quote! {
            #sig {
                #body
            }
        }
    }
    fn into_output_file(self) -> File {
        File {
            items: self.output,
            shebang: None,
            attrs: Vec::new(),
        }
    }
    fn find_function(
        &self,
        module_path: &[String],
        resource: &Option<String>,
        func: &Ident,
    ) -> Option<&Signature> {
        let module = self.funcs.get(module_path)?;
        let funcs = module.get(resource)?;
        funcs.iter().find(|sig| sig.ident == *func)
    }
}

pub fn get_proxy_path(src_path: &[String]) -> Vec<String> {
    assert!(src_path.len() >= 3);
    let mut res = src_path.to_vec();
    let mut wrapped_idx = 0;
    if res[0] == "exports" {
        res.remove(0);
    } else {
        res.insert(0, "exports".to_string());
        wrapped_idx = 1;
    }
    match res[wrapped_idx].strip_prefix("wrapped_") {
        Some(name) => res[wrapped_idx] = name.to_string(),
        None => res[wrapped_idx] = "wrapped_".to_string() + &res[wrapped_idx],
    }
    res
}
