[package]
name = "debug"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen.workspace = true
getrandom = "0.3"
libc-alloc = { path = "../../crates/libc-alloc", optional = true }

[features]
# Link with 1-byte wasm pages (see build.rs)
one-byte-page = ["dep:libc-alloc"]
